# This is a basic workflow to help you get started with Actions

name: README to startup event 

# Triggers the workflow on changes to readme.md
on:
  push:
    paths:
      - 'README.md'
    tags-ignore:
      - '*' #ignore tags pushes   
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  generate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - run: git fetch --prune --unshallow
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@master"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    - uses: actions/setup-python@v1
    - name: Install dependencies for python
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: python
      #run the python script
    - name: Run pyhton
      working-directory: python
      run: python OnReadMePush.py --verionNumber ${{ steps.previoustag.outputs.tag }}
    - name: Commit to repository
      run: |
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        git add .
        git commit -am "pushed by Github workflow OnReadMePush.yml using sript python.OnReadMePush.py "
        git push
    env:
      GITHUB_TOKEN: ${{ secrets.github_token }}
